CMU-IDeeL/CMU-IDeeL.github.io

- F21/index.html
> Added lec9 slides

- F21/index.html
> Updated slide 9 location

- F21/index.html
> Added lec25 slides

- S22/index.html
hw0p1 and hw0p2 handout download links broken; fixed it
> update index.html for hw0

- S22/index.html
update OH schedule, latest up to 8:50 pm on Jan 10
> Update OH schedule

- S22/index.html
> Added lec2 MT link

- S22/index.html
> Added lec5 recording

- S22/index.html
> Added lec 3 & 4 MT

- S22/index.html
> Added lec7 YT link

- S22/index.html
Corrected recitation 4 YT link
> Corrected rec4 YT link

- shared/TAs.html
I'll create an issue to add more formatting to the Acknowledgement page for later follow up :)
> Adding S22 TAs to Acknowledgment

- .gitignore
- F22/index.html
1. Making mobile menu consistent
2. Fixing Space before AM - Recitation timings description
3. Fixing details in Homework Hackathon
4. Adding .vscode to gitignore
> Minor fixes

- F22/index.html
1. Added zoom link to the class on the top of the website.
2. Updating TA list to as it is on the logistics sheet except for Rana as was updated before.
> Updating TA list and adding zoom link to class

- F22/index.html
Google Calendar is now forced to EST timezone.
> Fixing timezone issue on Google Calendar. 

- F22/index.html
Adding Lecture 3 video and Resources to page
> Adding Lecture 3 video and Resources to page

- F22/index.html
> Launching Quiz 1

- F22/index.html
> FIxing Hopfield typo

- F22/index.html
> Adding OH Calendar

- F22/index.html
Updating Karan's zoom link on his request
> Updating Karan's zoom link on his request

- F22/index.html
1. Karan's other OH link updated
2. Vish's Name in OH Fixed
3. Vish's OH Schedule fixed
4. OH Link moved to calendar
> Bulk fixes to OH section

- F22/index.html
Changing OH Links for Samruddhi and Vish
> Changing OH Links

- F22/index.html
Adding lecture 4 YT Video and Quiz 2 Link
> Adding lecture 4 YT Video and Quiz 2 Link

- F22/index.html
Updated:
1. Lecture 5 slides
2. Lecture 5 video links
3. Oscar's OH link (though I see Apa already fixed that so merged that branch)
> OH Link updates and Lecture 5 Links and slides

- F22/index.html
> Linking lecture 6

- F22/index.html
and some nice to have forwardings.
> Changing in person location for Aditya's OH

- F22/index.html
> Adding lecture 9 slides

- F22/index.html
1. YT Link for Lec 20
2. Slides for Lec 21
3. YT Link for Rec 11 - Part 1
> Link updates (See description)

- S23/index.html
> S23 eshani

- .gitignore
- F23/index.html
- Added OHs
- Added two new TAs on the list of TAs
> OHs uploaded and TAs list Updated

- F24/index.html
Update on August 11 2024 by Yuzhou Wang
> Update F24 Recitation Video Links

- F24/index.html
- S24/index.html
- S25/index.html
- index.html
S25 webpage as the homepage of the website
> S25 homepage

- F25/page/tables/lectures_table.html
- F25/page/tables_data/lectures.yaml
- Added a link to the slides for lecture 14 in the lectures table HTML.
- Updated the lectures.yaml file to include the slides URL and text for lecture 14.
> Add link to lecture 14 slides in lectures table and update YAML data
